"""Joint score distribution: bivariate model, key numbers, and simulation."""

from __future__ import annotations

from ncaa_quant.distribution.bivariate import (
    BivariateError,
    BivariateParams,
    RhoEstimate,
    assemble_bivariate,
    estimate_rho,
    estimate_rho_from_frame,
    residuals_from_predictions,
)
from ncaa_quant.distribution.key_numbers import (
    DEFAULT_MU_ABS_EDGES,
    ConditionalKeyNumberKernel,
    KeyNumberBucketValidation,
    KeyNumberError,
    KeyNumberKernel,
    continuous_integer_mass,
    discrete_margin_pmf,
    fit_key_number_kernel,
    sample_discrete_margins,
    validate_key_number_kernel,
)
from ncaa_quant.distribution.simulate import (
    DEFAULT_EPISTEMIC_DRAWS,
    DEFAULT_N_DRAWS,
    EpistemicMixture,
    JointDraws,
    MarketProbabilities,
    SimulateError,
    american_to_implied,
    brier_score,
    crps_gaussian,
    default_epistemic_draws,
    log_loss,
    mix_epistemic_predictions,
    moneyline_probs,
    pit_values,
    probs_sum_to_one,
    proportional_devig,
    reliability_curve,
    sample_bivariate_normal,
    sample_joint,
    save_pit_histogram,
    save_reliability_diagram,
    spread_cover_probs,
    total_probs,
    two_way_probs_sum_to_one,
    two_way_side_prob,
)

__all__ = [
    "DEFAULT_EPISTEMIC_DRAWS",
    "DEFAULT_N_DRAWS",
    "BivariateError",
    "BivariateParams",
    "EpistemicMixture",
    "JointDraws",
    "DEFAULT_MU_ABS_EDGES",
    "ConditionalKeyNumberKernel",
    "KeyNumberBucketValidation",
    "KeyNumberError",
    "KeyNumberKernel",
    "MarketProbabilities",
    "RhoEstimate",
    "SimulateError",
    "american_to_implied",
    "assemble_bivariate",
    "brier_score",
    "continuous_integer_mass",
    "crps_gaussian",
    "default_epistemic_draws",
    "discrete_margin_pmf",
    "estimate_rho",
    "estimate_rho_from_frame",
    "fit_key_number_kernel",
    "log_loss",
    "mix_epistemic_predictions",
    "moneyline_probs",
    "pit_values",
    "probs_sum_to_one",
    "proportional_devig",
    "reliability_curve",
    "residuals_from_predictions",
    "sample_bivariate_normal",
    "sample_discrete_margins",
    "sample_joint",
    "save_pit_histogram",
    "save_reliability_diagram",
    "spread_cover_probs",
    "total_probs",
    "two_way_probs_sum_to_one",
    "two_way_side_prob",
    "validate_key_number_kernel",
]
