"""Feature builders package (efficiency, tempo, situational, market, roster)."""

from ncaa_quant.features.builders.efficiency import (
    DEFAULT_RIDGE_LAMBDA,
    FCS_TIER_ENTITY,
    EfficiencyConfig,
    EfficiencyFeatureBuilder,
    bayesian_shrink,
    build_play_game_observations,
    ewma_final,
    ewma_sequence,
    last_n_delta,
    ridge_opponent_adjust,
    season_end_adjusted_epa,
)
from ncaa_quant.features.builders.roster import (
    DEFAULT_RECRUITING_WEIGHTS,
    PORTAL_ERA_START,
    RosterConfig,
    RosterFeatureBuilder,
    build_qb_status_frame,
    build_roster_frame,
    load_coordinators,
    portal_net_rating,
    scrape_depth_chart_qb_status,
    set_qb_status,
    weighted_recruiting_composite,
)
from ncaa_quant.features.builders.situational import (
    SituationalFeatureBuilder,
    build_situational_frame,
    haversine_km,
    load_rivalry_pairs,
    rest_days_between,
    tz_crossed_signed,
)
from ncaa_quant.features.builders.tempo import (
    ExpectedPossessionsArtifact,
    ExpectedPossessionsFeatureBuilder,
    TempoConfig,
    TempoFeatureBuilder,
    build_tempo_observations,
    fit_expected_possessions,
)

__all__ = [
    "DEFAULT_RECRUITING_WEIGHTS",
    "DEFAULT_RIDGE_LAMBDA",
    "FCS_TIER_ENTITY",
    "PORTAL_ERA_START",
    "EfficiencyConfig",
    "EfficiencyFeatureBuilder",
    "ExpectedPossessionsArtifact",
    "ExpectedPossessionsFeatureBuilder",
    "RosterConfig",
    "RosterFeatureBuilder",
    "SituationalFeatureBuilder",
    "TempoConfig",
    "TempoFeatureBuilder",
    "bayesian_shrink",
    "build_play_game_observations",
    "build_qb_status_frame",
    "build_roster_frame",
    "build_situational_frame",
    "build_tempo_observations",
    "ewma_final",
    "ewma_sequence",
    "fit_expected_possessions",
    "haversine_km",
    "last_n_delta",
    "load_coordinators",
    "load_rivalry_pairs",
    "portal_net_rating",
    "rest_days_between",
    "ridge_opponent_adjust",
    "scrape_depth_chart_qb_status",
    "season_end_adjusted_epa",
    "set_qb_status",
    "tz_crossed_signed",
    "weighted_recruiting_composite",
]
