"""Betting layer: de-vig, edges, EV, Kelly staking, filters, and CLV."""

from ncaa_quant.betting.clv import (
    CloseDefinition,
    ClvError,
    RecommendationRecord,
    SettledBet,
    WeeklyClvReport,
    assert_distinct_line_sources,
    compute_clv,
    settle_recommendation,
    settle_week,
)
from ncaa_quant.betting.devig import (
    DEFAULT_DEVIG_METHOD,
    DevigError,
    DevigMethod,
    DevigMethodName,
    american_to_decimal,
    american_to_raw_implied,
    decimal_to_raw_implied,
    devig,
    devig_two_way,
    fair_prob_on_side,
    multiplicative_devig,
    proportional_devig,
    shin_devig,
)
from ncaa_quant.betting.edges import (
    BookPrice,
    EdgeError,
    EdgeResult,
    best_price,
    compute_edge,
    expected_value,
    market_fair_prob,
)
from ncaa_quant.betting.filters import (
    BetCandidate,
    FilterReason,
    FilterResult,
    default_betting_config,
    evaluate_filters,
)
from ncaa_quant.betting.kelly import (
    HARD_MAX_KELLY_FRACTION,
    HARD_MAX_STAKE_PCT,
    ExposureState,
    KellyError,
    StakeResult,
    full_kelly,
    recommended_stake,
)

__all__ = [
    "DEFAULT_DEVIG_METHOD",
    "HARD_MAX_KELLY_FRACTION",
    "HARD_MAX_STAKE_PCT",
    "BetCandidate",
    "BookPrice",
    "ClvError",
    "CloseDefinition",
    "DevigError",
    "DevigMethod",
    "DevigMethodName",
    "EdgeError",
    "EdgeResult",
    "ExposureState",
    "FilterReason",
    "FilterResult",
    "KellyError",
    "RecommendationRecord",
    "SettledBet",
    "StakeResult",
    "WeeklyClvReport",
    "american_to_decimal",
    "american_to_raw_implied",
    "best_price",
    "assert_distinct_line_sources",
    "compute_clv",
    "compute_edge",
    "decimal_to_raw_implied",
    "default_betting_config",
    "devig",
    "devig_two_way",
    "evaluate_filters",
    "expected_value",
    "fair_prob_on_side",
    "full_kelly",
    "market_fair_prob",
    "multiplicative_devig",
    "proportional_devig",
    "recommended_stake",
    "settle_recommendation",
    "settle_week",
    "shin_devig",
]
